#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 18 14:53:00 2020

@author: fatih
"""

import os
import subprocess
import sys
from shutil import rmtree
from pathlib import Path
import distro
from datetime import datetime
import apt
import random, string


def main():
    def update():
        try:
            cache = apt.Cache()
            cache.open()
            cache.update()
        except Exception as e:
            print(str(e))
            subupdate()

    def subupdate():
        subprocess.call(["apt", "update"],
                        env={**os.environ, 'DEBIAN_FRONTEND': 'noninteractive'})

    def fixbroken():
        subprocess.call(["apt", "install", "--fix-broken", "-yq"],
                        env={**os.environ, 'DEBIAN_FRONTEND': 'noninteractive'})

    def dpkgconfigure():
        subprocess.call(["dpkg", "--configure", "-a"],
                        env={**os.environ, 'DEBIAN_FRONTEND': 'noninteractive'})

    def aptclean():
        subprocess.call(["apt", "clean"],
                        env={**os.environ, 'DEBIAN_FRONTEND': 'noninteractive'})

    def externalrepo(key, sources, name):
        tmpkeyfilename = ''.join(random.choice(string.ascii_lowercase) for i in range(13))
        tmpkeyfile = open(os.path.join("/tmp", tmpkeyfilename), "w")
        tmpkeyfile.write(key)
        tmpkeyfile.flush()
        tmpkeyfile.close()
        tmpkey = os.path.join("/tmp", tmpkeyfilename)

        subprocess.call(["apt-key", "add", tmpkey])

        Path("/etc/apt/sources.list.d/").mkdir(parents=True, exist_ok=True)
        sdfile = open("/etc/apt/sources.list.d/" + name, "w")
        sdfile.write(sources)
        sdfile.flush()
        sdfile.close()

        if os.path.isfile(tmpkey):
            os.remove(tmpkey)

    def correctsourceslist():
        found = True
        source = ""
        codename = distro.codename().lower()
        now = datetime.now()

        if codename == "bullseye":
            source = "### The Official Amarok Package Repositories ###\n\n" \
                     "deb http://repo.amaroklinux.org/amarok bullseye main contrib non-free\n" \
                     "deb http://deb.debian.org/debian bullseye main contrib non-free\n" \
                     "# deb-src http://deb.debian.org/debian bullseye main contrib non-free\n\n" \
		     "deb http://deb.debian.org/debian bullseye-updates main contrib non-free\n" \
                     "# deb-src http://deb.debian.org/debian bullseye-updates main contrib non-free\n\n" \
                     "deb http://deb.debian.org/debian-security bullseye-security main contrib non-free\n" \
                     "# deb-src http://deb.debian.org/debian-security bullseye-security main contrib non-free\n\n" \
                     "### This section generated by Amarok Software at " + str(now) + " ###\n"
        elif codename == "testing":
            source = "### The Official Amarok Package Repositories ###\n\n" \
                     "deb http://repo.amaroklinux.org/rolling rolling main contrib non-free\n" \
                     "deb http://deb.debian.org/debian testing main contrib non-free\n" \
                     "# deb-src http://deb.debian.org/debian testing main contrib non-free\n\n" \
		     "deb http://deb.debian.org/debian testing-updates main contrib non-free\n" \
                     "# deb-src http://deb.debian.org/debian testing-updates main contrib non-free\n\n" \
                     "deb http://security.debian.org/debian-security testing-security main contrib non-free\n" \
                     "# deb-src http://security.debian.org/debian-security testing-security main contrib non-free\n\n" \
                     "### This section generated by Amarok Software at " + str(now) + " ###\n"
            else:
                found = False        
        elif codename == "bookworm":
            source = "### The Official Debian Package Repositories ###\n\n" \
		       "deb http://deb.debian.org/debian bookworm main contrib non-free\n" \
                     "# deb-src http://deb.debian.org/debian bookworm main contrib non-free\n\n" \
		       "deb http://deb.debian.org/debian bookworm-updates main contrib non-free\n" \
                     "# deb-src http://deb.debian.org/debian bookworm-updates main contrib non-free\n\n" \
                       "deb http://security.debian.org/debian-security bookworm-security main contrib non-free\n" \
                     "# deb-src http://security.debian.org/debian-security bookworm-security main contrib non-free\n\n" \
                     "### This section generated by Amarok Software at " + str(now) + " ###\n"
        else:
            found = False

        if found:
            rmtree("/etc/apt/sources.list.d", ignore_errors=True)
            rmtree("/var/lib/apt/lists/", ignore_errors=True)
            Path("/etc/apt/sources.list.d").mkdir(parents=True, exist_ok=True)
            sfile = open("/etc/apt/sources.list", "w")
            sfile.write(source)
            sfile.flush()
            sfile.close()
            aptclean()

    if len(sys.argv) > 1:
        if sys.argv[1] == "externalrepo":
            externalrepo(sys.argv[2], sys.argv[3], sys.argv[4])
            update()
        elif sys.argv[1] == "correctsourceslist":
            correctsourceslist()
        elif sys.argv[1] == "update":
            update()
        elif sys.argv[1] == "fixapt":
            correctsourceslist()
            subupdate()
            fixbroken()
            dpkgconfigure()
        else:
            print("unknown argument error")
    else:
        print("no argument passed")


if __name__ == "__main__":
    main()
